save_checkpoint_steps: 500
keep_checkpoint: 6
param_init_glorot: 'true'
seed: 0
early_stopping: 5
report_every: 500
valid_steps: 500
train_steps: 100000

dropout: 0.5
attention_dropout: 0.5

world_size: 1
gpu_ranks:
- 0

data: processed_final/avocado.spacy_tokenized.separate.copy
save_model: checkpoints_Orig_final/avocado.spacy_tokenized/vanilla1/model
pre_word_vecs_enc: processed_final/avocado.spacy_tokenized.separate.copy.embeddings.d100.enc.pt
pre_word_vecs_dec: processed_final/avocado.spacy_tokenized.separate.copy.embeddings.d100.dec.pt
word_vec_size: 100
rnn_size: 256
layers: 1
rnn_type: LSTM
encoder_type: rnn

batch_size: 64
optim: adagrad
learning_rate: 0.15
adagrad_accumulator_init: 0.1
max_grad_norm: 2.0
